export const initialCountry = {
  name: {
    en: 'Poland',
    da: 'Polen',
    ru: 'Польша',
    pl: 'Polska',
    ua: 'Польща',
    cz: 'Polsko',
    by: 'Польшча',
    pt: 'Polónia',
    es: 'Polonia',
    ro: 'Polonia',
    bg: 'Полша',
    de: 'Polen',
    fr: 'Pologne',
    nl: 'Polen',
    it: 'Polonia',
    cn: '波兰',
    zh: '波蘭',
    ee: 'Poola',
    jp: 'ポーランド',
    he: 'פולין',
    el: 'Πολωνία',
    ar: 'بولندا',
    tr: 'Polonya',
  },
  dial_code: '+48',
  code: 'PL',
  flag: '🇵🇱',
}
